### ISSUE TITLE
Add self-assigning role command for pronouns

### ISSUE THREAD

**Issue by maxcell** [partycorgi/corgo-bot#35]
### Commands

The command(s) that support this could be:

Adding pronouns:
```
!pronoun add <list of pronouns>
```

Removing pronouns:
```
!pronoun remove <list of pronouns>
```

### Technical Details

The more intricate details though are how should we allow for pronouns, should they always be a combination of two forms (`he/him`, `they/them`, etc.)? I think if we were doing `role_by_name` this would be the easiest way of doing it. So each would look like:

```
!pronoun add he/him
```

We'd probably also have like a help command that would potentially dump a list or points to a list we have.

Alternatively, a solution I'm sitting on is:

Take the list of pronouns expressed in the [Pronoun Island "database"][pronoun-database] and add two forms of each as a role name, take the list and add their respective role ids. Then any time we build, the file turns into structs and then we could just use those to match instead. A reason for this could be to keep an active list we have available for folks so it can be a lighter conversation of when we don't have the right way to express it.

### Resources about pronouns

Some resources around pronouns for prosperity:
- [Gender Pronouns from UWMilwaukee - Forms](https://uwm.edu/lgbtrc/support/gender-pronouns/#:~:text=What%20is%20a%20pronoun%3F,that%20you%20are%20talking%20about)
- [Pronoun Island - Usage](http://pronoun.is/)
- [Pronoun Island - Database][pronoun-database]
- [Prior Art Pronoun List from community member](https://docs.google.com/document/d/1-BNSdfHWSnTqTo-jt9YrJtuUb835CZtazNOopMy0UFM/edit)

[pronoun-database]: https://github.com/witch-house/pronoun.is/blob/master/resources/pronouns.tab

**Comment by maxcell** [comment]
A big reason why two forms are important is that through some neopronouns you may have similar spelling for one form but be expressing something else:
- `ze/zir`
- `ze/hir`
- `ze/zem`

**Comment by mdarrik** [comment]
Would some form of reaction role be more user friendly? At least until we got PCN accounts hooked up?

**Comment by maxcell** [comment]
Does that pose the same attack vector with the members page we were concerned about? Isn't "searchable" but still a list. Regardless, it would be much easier for sure. Then we'd still need to map everything well, like converting `:ze-zir:` to the connected role `ze/zir`

**Comment by mdarrik** [comment]
It might be less searchable than a chat history? But that's a good point on it still being a list.

**Comment by maxcell** [comment]
I am really proud to say we can close this issue, we've opted for using [Pronoun Bot](https://support.discord.com/hc/en-us/articles/1500012528941-Pronoun-Picker-Bot-FAQ) which was good to add, add pronouns, and edit controls.

More information can be found on this page https://support.discord.com/hc/en-us/articles/1500012528941-Pronoun-Picker-Bot-FAQ
